services:
  - type: web
    name: zkp-server
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
